--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ItsMax123/KOTH
build-by-default: true
branches:
- master
projects:
  KOTH:
    path: ""
    icon: "koth.png"
    libs:
      - src: CortexPE/DiscordWebhookAPI/DiscordWebhookAPI
        version: 1.0.2
        branch: PM4
      - src: CortexPE/Commando/Commando
        version: 3.0.0
        branch: PM4
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: 0.1.3
        branch: pm5
    lint:
      phpstan: false
...
